#!/usr/bin/env bash
# setup.sh — interactive wizard that generates a project CLAUDE.md from the
# multi-agent-workflow template, capturing provider/model routing + project basics.
#
#   ./setup.sh                 generate CLAUDE.md in the current directory
#   ./setup.sh <project-dir>   generate CLAUDE.md in <project-dir>
#   ./setup.sh -h | --help     show this help
set -euo pipefail

usage() { sed -n '2,7p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }
case "${1:-}" in -h|--help) usage 0 ;; esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="$SCRIPT_DIR/templates/CLAUDE.md"

TARGET="${1:-$PWD}"
[ -d "$TARGET" ] || { echo "error: not a directory: $TARGET" >&2; exit 1; }
OUT="$TARGET/CLAUDE.md"

# choose "<prompt>" "opt1" "opt2" ... -> sets CHOICE to the selected option text.
choose() {
  local prompt="$1"; shift
  echo >&2; echo "$prompt" >&2
  local PS3="#? " opt
  select opt in "$@"; do
    [ -n "${opt:-}" ] && { CHOICE="$opt"; break; }
    echo "Enter a number from the list." >&2
  done
}

# ask "<prompt>" "<fallback>" -> echoes the entered value, or the fallback if empty.
ask() {
  local reply
  read -r -p "$1" reply || true
  printf '%s' "${reply:-$2}"
}

# Don't clobber an existing file without consent.
if [ -e "$OUT" ]; then
  choose "CLAUDE.md already exists at $OUT. What now?" \
    "Back it up to CLAUDE.md.bak and overwrite" \
    "Write to CLAUDE.generated.md instead" \
    "Cancel"
  case "$CHOICE" in
    Back*)  cp "$OUT" "$OUT.bak"; echo "backed up -> $OUT.bak" >&2 ;;
    Write*) OUT="$TARGET/CLAUDE.generated.md" ;;
    *)      echo "cancelled." >&2; exit 0 ;;
  esac
fi

echo "Generating $OUT — answer a few questions (Enter to accept defaults)." >&2

choose "Orchestrator (main session) model?" \
  "Claude Opus — strongest; best for planning & decomposition (recommended)" \
  "Claude Sonnet — cheaper orchestration for routine work" \
  "Session default — don't pin a model"
ORCHESTRATOR="$CHOICE"

choose "Implementation (writing scoped code) — who handles it?" \
  "Claude (Sonnet) — cheap, capable on scoped edits (recommended)" \
  "Claude (Opus) — maximum quality, higher cost" \
  "Codex — offload to OpenAI billing" \
  "Gemini — offload to Google billing"
IMPLEMENTATION="$CHOICE"

choose "Investigation / recon (read-only mapping) — who handles it?" \
  "Claude Explore/Haiku — cheap read-only recon (recommended)" \
  "Claude (Sonnet) — stronger recon" \
  "Codex" \
  "Gemini"
RECON="$CHOICE"

choose "Cross-model review — who handles it?" \
  "Codex — independent provider, separate billing (recommended)" \
  "Gemini — independent provider" \
  "Claude — a second Claude pass (least independent)" \
  "None — skip cross-model review"
REVIEW="$CHOICE"

echo >&2; echo "Project basics (Enter to leave as a placeholder):" >&2
STACK="$(ask "  Stack (e.g. TypeScript, React, Node, Postgres): " "<!-- fill in -->")"
PKG="$(ask "  Package manager / runtime (e.g. pnpm, uv, cargo): " "<!-- fill in -->")"
RUN="$(ask "  Run / build command (e.g. pnpm dev): " "<!-- fill in -->")"
TEST="$(ask "  Test command (e.g. pnpm test): " "<!-- fill in -->")"
LINT="$(ask "  Lint / format command (e.g. pnpm lint): " "<!-- fill in -->")"

# Single-source the behavioral rules from the template (between its two headings).
RULES=""
[ -f "$TEMPLATE" ] && RULES="$(awk '/^## Behavioral rules/{f=1} f&&/^## Project context/{exit} f{print}' "$TEMPLATE")"
[ -n "$RULES" ] || RULES=$'## Behavioral rules\n\n1. **Think before coding.** State assumptions; ask when ambiguous.\n2. **Simplicity first.** Minimum code that solves the problem.\n3. **Surgical changes.** Touch only what the task requires; match existing style.\n4. **Goal-driven execution.** Work to explicit success criteria and verify before declaring done.'

REVIEW_LINE="Run a cross-model review of non-trivial diffs against \`main\` using **${REVIEW%% —*}**."
[ "${REVIEW%% —*}" = "None" ] && REVIEW_LINE="Cross-model review is disabled for this project."

cat > "$OUT" <<EOF
# CLAUDE.md

> Generated by multi-agent-workflow \`setup.sh\` on $(date +%Y-%m-%d). Edit freely and grow it
> over time. Behavioral rules mirror the multi-agent-workflow reference repo
> (https://github.com/nscaamano/multi-agent-workflow).

## Provider & model routing

- **Orchestrator (main session):** $ORCHESTRATOR
- **Implementation:** $IMPLEMENTATION
- **Investigation / recon:** $RECON
- **Cross-model review:** $REVIEW

Reserve the strongest model for orchestration, push scoped implementation to the chosen worker,
keep recon cheap, and use the review provider for an independent second opinion. Provider choice
is a deliberate convention — there is no automatic router, so this file is what decides it.

## How this project uses the multi-agent workflow

- The main session is the **orchestrator**. Delegate real work to focused subagents.
- **Investigate in parallel** before planning; **split implementation** into independent pieces.
- **Match the model tier to the job** per the routing above.
- $REVIEW_LINE
- While workers run, observe their progress with \`/watch-agents\` (if the skill is installed).
- When you correct me on something, I should add a rule to this file so it doesn't recur.

$RULES

## Project context

- **Stack:** $STACK
- **Package manager / runtime:** $PKG
- **Run / build:** $RUN
- **Tests:** $TEST
- **Lint / format:** $LINT

## Conventions

<!-- Code style, naming, file layout, patterns to follow or avoid. -->

-

## Gotchas

<!-- Add a line every time the agent makes a mistake, so it doesn't repeat it. -->

-
EOF

echo >&2
echo "Wrote $OUT" >&2
echo "Review it, fill in any placeholders, and commit it to your project." >&2
